services:
  claude-code-proxy:
    container_name: claude-code-proxy
    image: crpi-0t50b9e7uk19r5o7.cn-shanghai.personal.cr.aliyuncs.com/await29/claudecodeproxy/koala-ai/claude-code-proxy
    ports:
      - "6500:6500"    # HTTP端口
    environment:
      - ConnectionStrings:DefaultConnection=Data Source=/app/data/ClaudeCodeProxy.db;Cache=Shared
      - RunMigrationsAtStartup=true
      - USER_NAME=admin
      - PASSWORD=admin123
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/ClaudeCodeProxy.Host/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
